name: absenin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  geolocator: ^5.3.1
  google_maps_flutter: ^0.5.25+3
  location: ^3.0.2
  flutter_launcher_icons: ^0.7.4
  sliding_up_panel: ^1.0.2
  image_picker: ^0.6.5
  flutter_native_splash: ^0.1.9
  flutter_icons: ^1.1.0
  pin_code_fields: ^2.5.1
  fluttertoast: ^4.0.1
  flutter_vant_kit: ^0.2.5
  modal_bottom_sheet: ^0.1.5
  simple_animations: ^2.1.1
  flutter_vibrate: ^1.0.0
  flutter_time_picker_spinner: ^1.0.6
  horizontal_time_picker: ^1.0.1
  photo_view: ^0.9.2
  flutter_datetime_picker: ^1.2.5
  file_picker: ^1.6.2
  random_color: ^1.0.5
  package_info: ^0.4.0+17
  device_info: ^0.4.2+3
  intl: ^0.16.1
  country_list_pick: ^1.0.0+2
  md2_tab_indicator: ^1.0.2
  some_calendar: ^1.2.2
  jiffy: ^3.0.1
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.5
  flutter_image_compress: ^0.6.8
  random_string: ^2.0.1
  bezier_chart: ^1.0.17+1
  path_provider: ^1.6.9
  shared_preferences: ^0.5.7+3
  content_placeholder: ^0.1.0
  flutter_email_sender: ^3.0.1
  advance_pdf_viewer: ^1.1.6
  flutter_local_notifications: ^1.4.3
  mailer: ^3.0.4
  http: ^0.12.1
  date_range_picker: ^1.0.5
  url_launcher: ^5.2.2
  slide_digital_clock: ^1.0.0
  pull_to_refresh: ^1.6.0
  cached_network_image: ^2.2.0+1
  time_machine: ^0.9.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/absenin_icon.png"
  android: true
  ios: true

flutter_native_splash:
  image: "assets/images/absenin.png"
  color: "ffffff"
  android_disable_fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/absenin_icon.png
    - assets/images/absenin.png
    - assets/images/pin.png
    - assets/images/pin_store.png
    - assets/images/pin_user.png
    - assets/images/img2.png
    - assets/images/img8.png
    - assets/images/img9.png
    - assets/images/schedule.png
    - assets/images/report.png
    - assets/images/staff.png
    - assets/images/approve.png
    - assets/images/acc.png
    - assets/images/history.png
    - assets/images/ovt.png
    - assets/images/fun.png
    - assets/images/help.png
    - assets/images/switch1.png
    - assets/images/permit.png
    - assets/images/cinemas.png
    - assets/images/empty.png
    - assets/images/nodata.png
    - assets/images/delete.png
    - assets/images/schedulespv.png
    - assets/images/main.png
    - assets/images/reject.png
    - assets/images/3173111070.jpg
    - assets/images/interaction.png
    - assets/styles/normal_style_maps.txt
    - assets/styles/night_style_maps.txt
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: "Google"
      fonts:
        - asset: assets/fonts/Google-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Google-Sans-Bold.ttf
        - asset: assets/fonts/Google-Sans-Italic.ttf
        - asset: assets/fonts/Google-Sans-Regular.ttf

    - family: "Sans"
      fonts:
        - asset: assets/fonts/Sans-Francisco.otf

    - family: "OpenSans"
      fonts:
        - asset: assets/fonts/OpenSansCondensed-Bold.ttf
        - asset: assets/fonts/OpenSansCondensed-Light.ttf
        - asset: assets/fonts/OpenSansCondensed-LightItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
